
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 26 23:11:20 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 19;
  public static final int LBRACKET = 42;
  public static final int CONST = 10;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 40;
  public static final int SEMI = 37;
  public static final int GREATER = 31;
  public static final int CONTINUE = 9;
  public static final int INTERFACE = 20;
  public static final int LESS = 33;
  public static final int MINUS = 24;
  public static final int RPAREN = 41;
  public static final int AND = 34;
  public static final int LESSEQUAL = 32;
  public static final int OR = 35;
  public static final int COMMA = 38;
  public static final int CLASS = 7;
  public static final int INC = 21;
  public static final int DIV = 26;
  public static final int PLUS = 22;
  public static final int ASSIGN = 36;
  public static final int IF = 11;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 28;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int NUMBER = 47;
  public static final int MOD = 27;
  public static final int IDENT = 48;
  public static final int BREAK = 6;
  public static final int VOID = 5;
  public static final int GREATEREQUAL = 30;
  public static final int UNION = 16;
  public static final int LBRACE = 44;
  public static final int ELSE = 8;
  public static final int READ = 13;
  public static final int CHARCONST = 49;
  public static final int WHILE = 18;
  public static final int RBRACE = 45;
  public static final int BOOLCONST = 46;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int DEC = 23;
  public static final int PRINT = 3;
  public static final int DO = 17;
  public static final int SET = 15;
}

